# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import toasauti.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, verbose_name=b'First Name')),
                ('lastName', models.CharField(max_length=20, verbose_name=b'Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name=b'Email Address')),
                ('message', models.TextField(max_length=500, verbose_name=b'Message')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carRegNo', models.CharField(max_length=50, verbose_name=b'Car Registration Number')),
                ('vehicleType', models.CharField(choices=[(b'PR', b'Private Vehicle'), (b'PB', b'Public Vehicle'), (b'MC', b'Motor Cycle')], max_length=20, verbose_name=b'Vehicle Type')),
                ('offenceType', models.CharField(choices=[(b'RD', b'Reckless Driving'), (b'HR', b'Harassment'), (b'BR', b'Bribery'), (b'HNR', b'Hit and Run'), (b'SP', b'Speeding'), (b'AC', b'Accident'), (b'OT', b'Other')], max_length=20, verbose_name=b'Offence Type')),
                ('offenceDescription', models.TextField(max_length=400, verbose_name=b'Offence Description')),
                ('location', models.CharField(max_length=200, verbose_name=b'Location')),
                ('time', models.DateField(default=django.utils.timezone.now, verbose_name=b'Date')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=toasauti.models.upload_img_path, verbose_name=b'Image(s)')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to=toasauti.models.upload_vid_path, verbose_name=b'Video(s)')),
                ('audio', models.FileField(blank=True, default=None, null=True, upload_to=toasauti.models.upload_aud_path, verbose_name=b'Audio(s)')),
                ('userEmail', models.EmailField(default=None, max_length=20, verbose_name=b'Email')),
                ('userPhoneNumber', models.CharField(default=None, max_length=20, verbose_name=b'Phone Number')),
                ('userNames', models.CharField(default=None, max_length=200, verbose_name=b'Reported By')),
                ('userIDNumber', models.CharField(default=None, max_length=20, verbose_name=b'ID Number')),
                ('followedUp', models.BooleanField(default=0, max_length=10, verbose_name=b'Has it been followed up and logged')),
            ],
        ),
    ]
