# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toasauti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='details',
            field=models.TextField(default=None, max_length=500, verbose_name=b'Details'),
        ),
    ]
