# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toasauti', '0002_report_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name=b'Details'),
        ),
    ]
